# Generated by Django 3.1.2 on 2022-11-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='aadharno',
            field=models.BigIntegerField(default=0),
        ),
    ]
