# Generated by Django 3.1.2 on 2022-11-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_account_aadharno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='requestedstatus',
            field=models.BooleanField(default=False),
        ),
    ]
