# Generated by Django 3.1.2 on 2022-11-23 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tbl_bookissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_bookissue',
            name='date_of_request',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
