# Generated by Django 3.1.2 on 2022-11-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tbl_bookissue_date_of_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_bookissue',
            old_name='date_of_request',
            new_name='date_of_issue',
        ),
    ]
