# Generated by Django 3.1.2 on 2023-02-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_tbl_returnbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Returnbook',
        ),
    ]
