# Generated by Django 3.1.2 on 2023-02-22 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_tbl_bookreturn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_bookreturn',
            old_name='issue_id',
            new_name='issue',
        ),
    ]
