# Generated by Django 3.1.2 on 2023-02-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20230222_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_bookreturn',
            old_name='issue',
            new_name='issue_id',
        ),
    ]
