# Generated by Django 3.1.2 on 2023-02-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230222_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_bookissue',
            name='issuedstatus',
            field=models.BooleanField(default=False),
        ),
    ]
