# Generated by Django 3.1.2 on 2023-02-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_tbl_bookissue_issuedstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bk_pdf',
            field=models.FileField(blank=0, default=0, null=0, upload_to=''),
        ),
    ]
