# Generated by Django 3.1.2 on 2023-02-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_book_bk_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bk_pdf',
            field=models.FileField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
