# Generated by Django 3.1.2 on 2023-02-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20230223_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bk_pdf',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
