# Generated by Django 3.1.2 on 2023-02-24 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230223_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_elibrary',
            fields=[
                ('ebookid', models.AutoField(primary_key=True, serialize=False)),
                ('bk_pdf', models.FileField(blank=True, null=True, upload_to='media')),
                ('bk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
            ],
        ),
    ]
