# Generated by Django 3.1.2 on 2023-02-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_book_bk_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_bookissue',
            name='date_of_issue',
            field=models.DateField(auto_now_add=True),
        ),
    ]
