# Generated by Django 3.1.2 on 2023-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20230225_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='elibrary',
            fields=[
                ('ebookid', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=50)),
                ('book_pdf', models.FileField(blank=True, default=0, null=True, upload_to='media')),
            ],
        ),
    ]
