# Generated by Django 3.1.2 on 2023-02-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_elibrary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elibrary',
            old_name='book_title',
            new_name='title',
        ),
    ]
