# Generated by Django 3.1.2 on 2023-02-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20230225_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elibrary',
            name='book_author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='elibrary',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
