# Generated by Django 3.1.2 on 2023-02-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20230225_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elibrary',
            name='book_pdf',
            field=models.FileField(blank=True, default=0, null=True, upload_to='pdf'),
        ),
    ]
