# Generated by Django 3.1.2 on 2023-02-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20230226_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='elibrary',
        ),
    ]
