# Generated by Django 3.1.2 on 2023-02-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_delete_elibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='elibrary',
            fields=[
                ('ebookid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('book_author', models.CharField(default='', max_length=50)),
                ('book_pdf', models.FileField(blank=True, default=0, null=True, upload_to='pdf')),
            ],
        ),
    ]
